import type { YakuQuestion } from './types'

const RON = { winType: 'ron', seatWind: 2, roundWind: 1 } as const

export const YAKU_QUESTIONS: readonly YakuQuestion[] = [
  {
    id: 'y01',
    level: 1,
    hand: '234567m345p456s88s',
    winTile: 'm6',
    context: RON,
    choices: ['tanyao', 'pinfu', 'iipeiko', 'yakuhai-seat'],
    hint: '1・9・字牌が1枚もないか確認しましょう。待ちの形にも注目',
  },
  {
    id: 'y02',
    level: 1,
    hand: '234567m345p456s88s',
    winTile: 'm7',
    context: RON,
    choices: ['pinfu', 'tanyao', 'menzen-tsumo', 'sanshoku-doujun'],
    hint: '同じ手でも和了牌が変わると役が変わります',
  },
  {
    id: 'y03',
    level: 1,
    hand: '123m456p789s99s555z',
    winTile: 'z5',
    context: RON,
    choices: ['yakuhai-haku', 'yakuhai-seat', 'toitoi', 'tanyao'],
    hint: '三元牌（白・發・中）の刻子はそれだけで役になります',
  },
  {
    id: 'y04',
    level: 2,
    hand: '234m456p123789s55z',
    winTile: 's1',
    context: { ...RON, riichi: true },
    choices: ['riichi', 'pinfu', 'tanyao', 'yakuhai-haku'],
    hint: '平和の条件「雀頭が役牌でない」に注意。白の雀頭は？',
  },
  {
    id: 'y05',
    level: 2,
    hand: '234m234p234s567m88s',
    winTile: 'm7',
    context: RON,
    choices: ['sanshoku-doujun', 'pinfu', 'tanyao', 'ittsu'],
    hint: '3色で同じ数字の順子がそろっていないか見ましょう',
  },
  {
    id: 'y06',
    level: 2,
    hand: '123m789m789p11z',
    winTile: 'm7',
    melds: [{ type: 'pon', tiles: ['s9', 's9', 's9'] }],
    context: RON,
    choices: ['chanta', 'junchan', 'honroutou', 'yakuhai-seat'],
    hint: '全ての面子と雀頭に1・9・字牌が含まれているか確認',
  },
  {
    id: 'y07',
    level: 3,
    hand: '123456789m45p66s3p',
    winTile: 'p3',
    context: RON,
    choices: ['ittsu', 'pinfu', 'sanshoku-doujun', 'chinitsu'],
    hint: '同色の123・456・789がそろうと一気通貫です',
  },
  {
    id: 'y08',
    level: 3,
    hand: '112233m778899p55s',
    winTile: 's5',
    context: RON,
    choices: ['ryanpeiko', 'chiitoi', 'iipeiko', 'pinfu'],
    hint: '七対子にも見えますが、より高く取れる解釈があります（高点法）',
  },
  {
    id: 'y09',
    level: 3,
    hand: '123456789m111z22z',
    winTile: 'm9',
    context: RON,
    choices: ['honitsu', 'chinitsu', 'ittsu', 'yakuhai-round', 'yakuhai-seat'],
    hint: '字牌が混ざった染め手と、東の刻子の扱いに注意（東場です）',
  },
  {
    id: 'y10',
    level: 4,
    hand: '111m222p333s44455z',
    winTile: 'z4',
    context: RON,
    choices: ['suuankou', 'sanankou', 'toitoi', 'sanshoku-doukou'],
    hint: 'ロンで完成した刻子は明刻扱いです。四暗刻は成立するでしょうか',
  },
  {
    id: 'y11',
    level: 4,
    hand: '123m789m123p789s11s',
    winTile: 'p3',
    context: RON,
    choices: ['junchan', 'chanta', 'honroutou', 'pinfu', 'iipeiko'],
    hint: '字牌を使わず全ブロックに1・9が絡むと純全帯幺九です',
  },
  {
    id: 'y12',
    level: 4,
    hand: '223344666s888s66z',
    winTile: 's8',
    context: { winType: 'tsumo', seatWind: 2, roundWind: 1 },
    choices: ['ryuuiisou', 'honitsu', 'daisangen', 'tsuuiisou'],
    hint: '緑色の牌だけで構成された役満があります',
  },
]
